### ISSUE TITLE
which version of boost can be used

### ISSUE THREAD

**Issue by qgking** [mbickel/DenseInferenceWrapper#14]
env:
 python2.7
 boost-python 1.66
 when i run test_CRFProcessor.py, it occurs

> did not match C++ signature:
>     set_image(DenseCRF3DProcessor {lvalue}, boost::python::numeric::array, int, int, int, std::string

 is it the wrong verison of boost-python???

**Comment by qgking** [comment]
finaly i use 1.58. it works

**Comment by anewlearner** [comment]
@qgking I installed boost 1.58 and changed the BOOST_INC in the makefile. But the error was still there. Is anything else is needed?
